apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-886eef93-f40a-4b2c-887b-dda9b685cc60
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
